config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"

  resources :lists do
    resources :bookmarks do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'already bookmarked' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create, :destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  def new
    @list = List.new
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1 class="my-4 text-center">Choose a movie</h1>
  <div class="row justify-content-center">
    <div class="bg-light w-50 pt-4 px-4">

      <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie,
                        prompt: "Select a movie",
                        input_html: {data: {controller: "tom-select"}} %>
      <%= f.input :comment,
                  label_html: { class: "d-block text-center" },
                  input_html: { class: "form-control w-100 d-block mx-auto" } %>
      <div class="text-center py-4"><%= f.button :submit, class: "btn btn-dark btn-lg" %></div>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100">
  <!-- Header -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to "Mateo's lair", lists_path, class: "navbar-brand fw-bold" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "My Lists", lists_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'New list', new_list_path, class: "nav-link"%></li>
        </ul>
      </div>
    </div>
  </nav>
      <%= yield %>
  <!-- Footer -->
  <footer class="bg-dark text-white py-4 mt-auto">
    <div class="container text-center">
      <span>© 2025 Mateomaniac – All right reserved</span>
    </div>
  </footer>
  </body>
</html>

app/views/lists/index.html.erb
<!-- Banner -->
<section class="hero position-relative text-center text-white">
</section>

<!-- Cards -->
<div class="container">
<h1 class="my-4">My movies lists</h1>
  <div class="row g-2">
    <%  @lists.each do |list|%>
    <div class="col-4">
      <div class="card">
        <%= image_tag "placeholder.png", alt: "placeholder", class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-text"><%= link_to list.name, list_path(list) %></h5>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row justify-content-center my-4">
    <div class="col-3 text-center"><%= link_to 'New list', new_list_path, class: "btn btn-dark btn-lg"%></div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1 class="my-4 text-center">Create a movie list</h1>
  <div class="row justify-content-center">
    <div class="bg-light w-50 pt-4 px-4">

      <%= simple_form_for @list do |f| %>
        <%= f.input :name,
        label_html: { class: "d-block text-center" },
        input_html: { class: "form-control w-50 d-block mx-auto" } %>
        <div class="text-center py-4"><%= f.button :submit, class: "btn btn-dark btn-lg" %></div>
      <% end %>

    </div>
  </div>
</div>

app/views/lists/show.html.erb
<!-- Banner -->
<section class="hero position-relative text-center text-white">
</section>

<!-- movies cards -->
<div class="container">
<h1 class="my-4"><%= @list.name %></h1>
  <div class="row g-2">
    <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-4">
        <div class="card">
          <%= image_tag movie.poster_url, alt: "#{movie.title}", class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"><%= movie.overview %></p>
            <p class="card-text"><small class="text-muted"><%= bookmark.comment %></small></p>
            <p>
            <%= link_to 'Remove from list', list_bookmark_path(@list, bookmark),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
            class: "btn btn-dark btn-lg w-100"%>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row justify-content-center my-4">
    <div class="col-3 text-center"><%= link_to "Back", lists_path, class: "btn btn-secondary btn-lg w-100"%></div>
    <div class="col-3 text-center"><%= link_to 'Add movie', new_list_bookmark_path(@list), class: "btn btn-dark btn-lg w-100"%></div>
  </div>
</div>

<br><br><br>